---
run:
  timeout: 3m
linters:
  enable:
    - bodyclose
    - exportloopref
    - gofmt
    - gosec
    - govet
    - misspell
    - noctx
    - staticcheck
    - unconvert
    - unparam
    - whitespace
issues:
  max-same-issues: 0
linters-settings:
  goimports:
    local-prefixes: github.com/jakekeeys/hg612-exporter
  misspell:
    locale: US
